export CODE_HOME="$HOME/Code"
export DOTFILES_HOME="$HOME/Code/dotfiles"

alias  bp="vim ~/.bash_profile"
alias  rc="vim ~/.bashrc"
alias  so=". ~/.bash_profile"

alias  data="cd $CODE_HOME/Data_analysis; Jupyter notebook"
alias  code="cd $CODE_HOME"
alias  site="cd $CODE_HOME/sites"
alias  model="cd $CODE_HOME/Data_analysis/First/predictive-model"
alias  nmodel="cd $CODE_HOME/Data_analysis/First/predictive-model/ipython/New_model-Ziyue_Li"
alias  batch="vim $CODE_HOME/Data_analysis/First/predictive-model/ipython/New_model-Ziyue_Li/lib/_resources/Batch_list.csv"
alias  combine="vim $CODE_HOME/Data_analysis/First/predictive-model/ipython/New_model-Ziyue_Li/_resources/Combine_list.csv"
alias  mixbatch="vim $CODE_HOME/Data_analysis/First/predictive-model/ipython/New_model-Ziyue_Li/_resources/Mix_scoring_list.csv"
alias  mrfolder="cd $CODE_HOME/Data_analysis/First/java-mapreduce"
alias  mrcode="cd $CODE_HOME/Data_analysis/First/java-mapreduce/src/main/java/io/first/mapreduce"
alias  cleanup="cd $CODE_HOME/Data_analysis/First/csv_clean_up"
alias  import="cd $CODE_HOME/Data_analysis/First/data_pipeline/Import_score"
alias  spark="cd $CODE_HOME/Data_analysis/First/spark/"
alias  vesta="cd $CODE_HOME/Data_analysis/First/vesta/"
alias  cortex="cd $CODE_HOME/Data_analysis/First/cortex/"
alias  pipeline="cd $CODE_HOME/Data_analysis/First/pipeline/"
alias  davinci="cd $CODE_HOME/Data_analysis/First/davinci/"